# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_current_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='description',
            field=models.TextField(blank=True, help_text='Optional', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='title',
            field=models.CharField(default='current', max_length=256, verbose_name='title'),
            preserve_default=False,
        ),
    ]
