# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-28 11:23
from __future__ import unicode_literals

from django.db import migrations


def set_project(apps, schema_editor):
    Value = apps.get_model('projects', 'Value')
    for value in Value.objects.all():
        value.project = value.snapshot.project
        value.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_values'),
    ]

    operations = [
        migrations.RunPython(set_project),
    ]
