# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0003_refactoring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='view',
            options={'ordering': ('uri',), 'verbose_name': 'View', 'verbose_name_plural': 'Views'},
        ),
        migrations.AddField(
            model_name='view',
            name='uri',
            field=models.URLField(blank=True, help_text='The Uniform Resource Identifier of this catalog (auto-generated).', max_length=640, null=True, verbose_name='URI'),
        ),
        migrations.AddField(
            model_name='view',
            name='uri_prefix',
            field=models.URLField(blank=True, help_text='The prefix for the URI of this catalog.', max_length=256, null=True, verbose_name='URI Prefix'),
        ),
        migrations.AlterField(
            model_name='view',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional information about this catalog.', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='view',
            name='key',
            field=models.SlugField(blank=True, help_text='The internal identifier of this catalog. The URI will be generated from this key.', max_length=128, null=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='view',
            name='template',
            field=models.TextField(blank=True, help_text='The template for this view, written in Django template language.', null=True, verbose_name='Template'),
        ),
    ]
