# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0017_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional internal information about this condition.', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='key',
            field=models.SlugField(blank=True, help_text='The internal identifier of this condition.', max_length=128, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='target_text',
            field=models.CharField(blank=True, help_text='If using a regular value, the text value this condition is checking against (for boolean values use 1 and 0).', max_length=256, verbose_name='Target (Text)'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='uri',
            field=models.URLField(blank=True, help_text='The Uniform Resource Identifier of this condition (auto-generated).', max_length=640, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='uri_prefix',
            field=models.URLField(blank=True, help_text='The prefix for the URI of this condition.', max_length=256, verbose_name='URI Prefix'),
        ),
    ]
