# Generated by Django 3.2.16 on 2023-02-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('conditions', '0022_condition_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this condition (in a multi site setup).', related_name='conditions_as_editor', to='sites.Site', verbose_name='Editors'),
        ),
    ]
