# Generated by Django 5.2.14 on 2026-06-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0025_alter_condition_uri_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='relation',
            field=models.CharField(choices=[('eq', 'is equal to (==)'), ('neq', 'is not equal to (!=)'), ('contains', 'contains'), ('gt', 'is greater than (>)'), ('gte', 'is greater than or equal (>=)'), ('lt', 'is less than (<)'), ('lte', 'is less than or equal (<=)'), ('empty', 'is empty'), ('notempty', 'is not empty')], help_text='The relation this condition is using.', max_length=8, verbose_name='Relation'),
        ),
    ]
