# Generated by Django 4.2.26 on 2025-11-14 14:00

from django.db import migrations, models
import rdmo.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sites', '0002_alter_domain_unique'),
        ('questions', '0097_alter_question_widget_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(editable=False, verbose_name='updated')),
                ('uri', models.URLField(blank=True, default='', help_text='The Uniform Resource Identifier of this plugin (auto-generated).', max_length=800, verbose_name='URI')),
                ('uri_prefix', models.URLField(help_text='The prefix for the URI of this plugin.', max_length=256, verbose_name='URI Prefix')),
                ('uri_path', models.CharField(blank=True, default='', help_text='The path for the URI of this plugin.', max_length=512, verbose_name='URI Path')),
                ('comment', models.TextField(blank=True, default='', help_text='Additional internal information about this question.', verbose_name='Comment')),
                ('locked', models.BooleanField(default=False, help_text='Designates whether this plugin can be changed.', verbose_name='Locked')),
                ('order', models.IntegerField(default=0, help_text='The position of this plugin in lists.', verbose_name='Order')),
                ('title_lang1', models.CharField(blank=True, help_text='The title for this plugin (in the primary language).', max_length=256, verbose_name='Title (primary)')),
                ('title_lang2', models.CharField(blank=True, help_text='The title for this plugin (in the secondary language).', max_length=256, verbose_name='Title (secondary)')),
                ('title_lang3', models.CharField(blank=True, help_text='The title for this plugin (in the tertiary language).', max_length=256, verbose_name='Title (tertiary)')),
                ('title_lang4', models.CharField(blank=True, help_text='The title for this plugin (in the quaternary language).', max_length=256, verbose_name='Title (quaternary)')),
                ('title_lang5', models.CharField(blank=True, help_text='The title for this plugin (in the quinary language).', max_length=256, verbose_name='Title (quinary)')),
                ('help_lang1', models.TextField(blank=True, help_text='The help text for this plugin (in the primary language).', verbose_name='Help (primary)')),
                ('help_lang2', models.TextField(blank=True, help_text='The help text for this plugin (in the secondary language).', verbose_name='Help (secondary)')),
                ('help_lang3', models.TextField(blank=True, help_text='The help text for this plugin (in the tertiary language).', verbose_name='Help (tertiary)')),
                ('help_lang4', models.TextField(blank=True, help_text='The help text for this plugin (in the quaternary language).', verbose_name='Help (quaternary)')),
                ('help_lang5', models.TextField(blank=True, help_text='The help text for this plugin (in the quinary language).', verbose_name='Help (quinary)')),
                ('available', models.BooleanField(default=True, help_text='Designates whether this plugin is generally available for projects.', verbose_name='Available')),
                ('python_path', models.CharField(help_text='Python dotted path to the plugin class, e.g. "rdmo_plugins_provider.module.PluginClass"', max_length=512, verbose_name='Python path')),
                ('plugin_settings', models.JSONField(blank=True, default=dict, help_text='Contains the settings for this plugin in JSON format.', verbose_name='Plugin settings')),
                ('plugin_meta', models.JSONField(blank=True, default=dict, editable=False, help_text='Contains metadata derived from the plugin class.', verbose_name='Plugin metadata')),
                ('plugin_type', models.SlugField(blank=True, default='', editable=False, help_text='The type of plugin this is, e.g. "project_export".', max_length=128, verbose_name='Plugin type',
                    choices=[('project_export', 'Project export'), ('project_snapshot_export', 'Project snapshot export'), ('project_import', 'Project import'), ('project_issue_provider', 'Project issue provider'), ('optionset_provider', 'Optionset provider')])),
                ('url_name', models.SlugField(blank=True, default='', help_text='The url_name for this plugin.', max_length=128, verbose_name='URL name')),
                ('catalogs', models.ManyToManyField(blank=True, help_text='The catalogs this plugin can be used with. An empty list implies that this plugin can be used with every catalog.', to='questions.catalog', verbose_name='Catalogs')),
                ('editors', models.ManyToManyField(blank=True, help_text='The sites that can edit this plugin (in a multi site setup).', related_name='plugins_as_editor', to='sites.site', verbose_name='Editors')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups for which this plugin is active.', to='auth.group', verbose_name='Group')),
                ('sites', models.ManyToManyField(blank=True, help_text='The sites this plugin belongs to (in a multi site setup).', to='sites.site', verbose_name='Sites')),
            ],
            options={
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
                'ordering': ('uri', 'order'),
            },
            bases=(models.Model, rdmo.core.models.TranslationMixin),
        ),
    ]
