# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='parent_entity',
            new_name='parent',
        ),
    ]
