# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_renaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='full_title_de',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='full_title_en',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsection',
            name='full_title_de',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsection',
            name='full_title_en',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
