# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0010_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('optionset__order', 'order'), 'permissions': (('view_option', 'Can view Option'),), 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='optionset',
            options={'ordering': ('uri',), 'permissions': (('view_optionset', 'Can view Option set'),), 'verbose_name': 'Option set', 'verbose_name_plural': 'Option sets'},
        ),
    ]
