# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0018_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional internal information about this option.', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='option',
            name='key',
            field=models.SlugField(blank=True, help_text='The internal identifier of this option.', max_length=128, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='option',
            name='path',
            field=models.SlugField(blank=True, help_text='The path part of the URI for this option (auto-generated).', max_length=512, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text_lang1',
            field=models.CharField(blank=True, help_text='The text for this option in the primary language.', max_length=256, verbose_name='Text (primary)'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text_lang2',
            field=models.CharField(blank=True, help_text='The text for this option in the secondary language.', max_length=256, verbose_name='Text (secondary)'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text_lang3',
            field=models.CharField(blank=True, help_text='The text for this option in the tertiary language.', max_length=256, verbose_name='Text (tertiary)'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text_lang4',
            field=models.CharField(blank=True, help_text='The text for this option in the quaternary language.', max_length=256, verbose_name='Text (quaternary)'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text_lang5',
            field=models.CharField(blank=True, help_text='The text for this option in the quinary language.', max_length=256, verbose_name='Text (quinary)'),
        ),
        migrations.AlterField(
            model_name='option',
            name='uri',
            field=models.URLField(blank=True, help_text='The Uniform Resource Identifier of this option (auto-generated).', max_length=640, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='option',
            name='uri_prefix',
            field=models.URLField(blank=True, help_text='The prefix for the URI of this option.', max_length=256, verbose_name='URI Prefix'),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional internal information about this option set.', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='key',
            field=models.SlugField(blank=True, help_text='The internal identifier of this option set.', max_length=128, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='uri',
            field=models.URLField(blank=True, help_text='The Uniform Resource Identifier of this option set (auto-generated).', max_length=640, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='uri_prefix',
            field=models.URLField(blank=True, help_text='The prefix for the URI of this option set.', max_length=256, verbose_name='URI Prefix'),
        ),
    ]
