# Generated by Django 3.2.12 on 2022-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0026_optionset_option_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionset',
            name='locked',
            field=models.BooleanField(default=False, help_text='Designates whether this option set (and its options) can be changed.', verbose_name='Locked'),
        ),
    ]
