# Generated by Django 3.2.14 on 2023-01-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0027_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('uri',), 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.RenameField(
            model_name='optionset',
            old_name='key',
            new_name='uri_path',
        ),
        migrations.AlterField(
            model_name='optionset',
            name='uri',
            field=models.URLField(blank=True, help_text='The Uniform Resource Identifier of this option set (auto-generated).', max_length=800, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='uri_path',
            field=models.CharField(blank=True, help_text='The path for the URI of this option set.', max_length=512, verbose_name='URI Path'),
        ),
    ]
