# Generated by Django 3.2.14 on 2023-01-10 14:05

from django.db import migrations, models
import django.db.models.deletion


def run_data_migration(apps, schema_editor):
    Option = apps.get_model('options', 'Option')

    for option in Option.objects.all():
        option.optionset.options.add(option)


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0029_option_uri_path'),
    ]

    operations = [
        # remove the related_name='options' from Option.optionset
        migrations.AlterField(
            model_name='option',
            name='optionset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='options.OptionSet'),
        ),
        migrations.AddField(
            model_name='optionset',
            name='options',
            field=models.ManyToManyField(blank=True, help_text='The list of options for this option set.', related_name='optionsets', to='options.Option', verbose_name='Options'),
        ),
        migrations.RunPython(run_data_migration),
        migrations.RemoveField(
            model_name='option',
            name='optionset',
        )
    ]
