# Generated by Django 3.2.14 on 2023-01-10 14:05

from django.db import migrations, models


def run_data_migration(apps, schema_editor):
    Option = apps.get_model('options', 'Option')

    for option in Option.objects.all():
        option.optionsets.add(option.optionset)


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0029_option_uri_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='optionsets',
            field=models.ManyToManyField(blank=True, help_text='The list of optionsets this option belongs to.', related_name='options', to='options.OptionSet', verbose_name='Option sets'),
        ),
        migrations.RunPython(run_data_migration),
        migrations.RemoveField(
            model_name='option',
            name='optionset',
        )
    ]
