# Generated by Django 3.2.16 on 2023-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('options', '0030_optionset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this option (in a multi site setup).', related_name='options_as_editor', to='sites.Site', verbose_name='Editors'),
        ),
        migrations.AddField(
            model_name='optionset',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this option set (in a multi site setup).', related_name='optionsets_as_editor', to='sites.Site', verbose_name='Editors'),
        ),
    ]
