# Generated by Django 4.2.5 on 2023-09-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('options', '0031_add_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='editors',
            field=models.ManyToManyField(
                blank=True,
                help_text='The sites that can edit this option (in a multi site setup).',
                related_name='%(class)s_editors',
                to='sites.site',
                verbose_name='Editors',
            ),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='editors',
            field=models.ManyToManyField(
                blank=True,
                help_text='The sites that can edit this option set (in a multi site setup).',
                related_name='%(class)s_editors',
                to='sites.site',
                verbose_name='Editors',
            ),
        ),
    ]
