# Generated by Django 4.2.5 on 2023-10-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0032_alter_option_additional_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='help_lang1',
            field=models.TextField(blank=True, help_text='The help text for this option in the primary language.', null=True, verbose_name='Help (primary)'),
        ),
        migrations.AddField(
            model_name='option',
            name='help_lang2',
            field=models.TextField(blank=True, help_text='The help text for this option in the secondary language.', null=True, verbose_name='Help (secondary)'),
        ),
        migrations.AddField(
            model_name='option',
            name='help_lang3',
            field=models.TextField(blank=True, help_text='The help text for this option in the tertiary language.', null=True, verbose_name='Help (tertiary)'),
        ),
        migrations.AddField(
            model_name='option',
            name='help_lang4',
            field=models.TextField(blank=True, help_text='The help text for this option in the quaternary language.', null=True, verbose_name='Help (quaternary)'),
        ),
        migrations.AddField(
            model_name='option',
            name='help_lang5',
            field=models.TextField(blank=True, help_text='The help text for this option in the quinary language.', null=True, verbose_name='Help (quinary)'),
        ),
    ]
