# Generated by Django 4.2.5 on 2023-10-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0033_option_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='view_text_lang1',
            field=models.TextField(blank=True, help_text='The view text for this option in the primary language.', null=True, verbose_name='View text (primary)'),
        ),
        migrations.AddField(
            model_name='option',
            name='view_text_lang2',
            field=models.TextField(blank=True, help_text='The view text for this option in the secondary language.', null=True, verbose_name='View text (secondary)'),
        ),
        migrations.AddField(
            model_name='option',
            name='view_text_lang3',
            field=models.TextField(blank=True, help_text='The view text for this option in the tertiary language.', null=True, verbose_name='View text (tertiary)'),
        ),
        migrations.AddField(
            model_name='option',
            name='view_text_lang4',
            field=models.TextField(blank=True, help_text='The view text for this option in the quaternary language.', null=True, verbose_name='View text (quaternary)'),
        ),
        migrations.AddField(
            model_name='option',
            name='view_text_lang5',
            field=models.TextField(blank=True, help_text='The view text for this option in the quinary language.', null=True, verbose_name='View text (quinary)'),
        ),
    ]
