# Generated by Django 4.2.7 on 2023-11-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0034_option_view_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="help_lang1",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for this option in the primary language.",
                verbose_name="Help (primary)",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="help_lang2",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for this option in the secondary language.",
                verbose_name="Help (secondary)",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="help_lang3",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for this option in the tertiary language.",
                verbose_name="Help (tertiary)",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="help_lang4",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for this option in the quaternary language.",
                verbose_name="Help (quaternary)",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="help_lang5",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for this option in the quinary language.",
                verbose_name="Help (quinary)",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="view_text_lang1",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The view text for this option in the primary language.",
                verbose_name="View text (primary)",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="view_text_lang2",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The view text for this option in the secondary language.",
                verbose_name="View text (secondary)",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="view_text_lang3",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The view text for this option in the tertiary language.",
                verbose_name="View text (tertiary)",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="view_text_lang4",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The view text for this option in the quaternary language.",
                verbose_name="View text (quaternary)",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="view_text_lang5",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The view text for this option in the quinary language.",
                verbose_name="View text (quinary)",
            ),
        ),
    ]
