# Generated by Django 4.2.26 on 2025-11-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('options', '0036_option_default_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionset',
            name='plugins',
            field=models.ManyToManyField(blank=True, help_text='The list of plugins evaluated for this option set.', related_name='optionsets', to='config.plugin', verbose_name='Plugins'),
        ),
    ]
