# Generated by Django 4.2.27 on 2026-01-09 09:10

from django.db import migrations


def migrate_optionset_provider_key(apps, schema_editor):
    OptionSet = apps.get_model('options', 'OptionSet')
    Plugin = apps.get_model('config', 'Plugin')

    providers = {
        plugin.url_name: plugin.id
        for plugin in Plugin.objects.filter(plugin_type='optionset_provider').exclude(url_name='')
    }

    if not providers:
        return

    through_model = OptionSet.plugins.through

    optionsets = OptionSet.objects.exclude(provider_key='').values('id', 'provider_key')
    for optionset in optionsets:
        plugin_id = providers.get(optionset['provider_key'])
        if plugin_id is None:
            continue

        through_model.objects.get_or_create(
            optionset_id=optionset['id'],
            plugin_id=plugin_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0037_optionset_plugins'),
    ]

    operations = [
        migrations.RunPython(migrate_optionset_provider_key, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='optionset',
            name='provider_key',
        ),
    ]