# Generated by Django 4.2.27 on 2026-01-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0037_optionset_plugins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionset',
            name='provider_key',
        ),
    ]
