# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-29 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0039_meta'),
        ('tasks', '0013_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='days_after',
            field=models.IntegerField(blank=True, help_text='Additional days after the end date.', null=True, verbose_name='Days after'),
        ),
        migrations.AddField(
            model_name='task',
            name='days_before',
            field=models.IntegerField(blank=True, help_text='Additional days before the start date.', null=True, verbose_name='Days before'),
        ),
        migrations.AddField(
            model_name='task',
            name='end_attribute',
            field=models.ForeignKey(blank=True, help_text='The attribute that is setting the end date for this task (optional, if no end date attribute is given, the start date attribute sets also the end date).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='domain.Attribute', verbose_name='End date attribute'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_attribute',
            field=models.ForeignKey(blank=True, help_text='The attribute that is setting the start date for this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='domain.Attribute', verbose_name='Start date attribute'),
        ),
    ]
