# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_rename_en_to_lang1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text_de',
            new_name='text_lang2',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title_de',
            new_name='title_lang2',
        ),
    ]
