# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional internal information about this task.', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='key',
            field=models.SlugField(blank=True, help_text='The internal identifier of this task.', max_length=128, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text_lang1',
            field=models.TextField(blank=True, help_text='The text for this task in the primary language.', verbose_name='Text (primary)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text_lang2',
            field=models.TextField(blank=True, help_text='The text for this task in the secondary language.', verbose_name='Text (secondary)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text_lang3',
            field=models.TextField(blank=True, help_text='The text for this task in the tertiary language.', verbose_name='Text (tertiary)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text_lang4',
            field=models.TextField(blank=True, help_text='The text for this task in the quaternary language.', verbose_name='Text (quaternary)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text_lang5',
            field=models.TextField(blank=True, help_text='The text for this task in the quinary language.', verbose_name='Text (quinary)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_lang1',
            field=models.CharField(blank=True, help_text='The title for this task in the primary language.', max_length=256, verbose_name='Title (primary)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_lang2',
            field=models.CharField(blank=True, help_text='The title for this task in the secondary language.', max_length=256, verbose_name='Title (secondary)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_lang3',
            field=models.CharField(blank=True, help_text='The title for this task in the tertiary language.', max_length=256, verbose_name='Title (tertiary)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_lang4',
            field=models.CharField(blank=True, help_text='The title for this task in the quaternary language.', max_length=256, verbose_name='Title (quaternary)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_lang5',
            field=models.CharField(blank=True, help_text='The title for this task in the quinary language.', max_length=256, verbose_name='Title (quinary)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='uri',
            field=models.URLField(blank=True, help_text='The Uniform Resource Identifier of this task (auto-generated).', max_length=640, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='task',
            name='uri_prefix',
            field=models.URLField(blank=True, help_text='The prefix for the URI of this task.', max_length=256, verbose_name='URI Prefix'),
        ),
    ]
