# Generated by Django 3.2.16 on 2023-02-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('tasks', '0033_task_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this task (in a multi site setup).', related_name='tasks_as_editor', to='sites.Site', verbose_name='Editors'),
        ),
    ]
