# Generated by Django 4.2.20 on 2025-04-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_alter_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uri_path',
            field=models.CharField(blank=True, default='', help_text='The path for the URI of this task.', max_length=512, verbose_name='URI Path'),
        ),
    ]
