# Generated by Django 5.2.12 on 2026-04-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_data_migration_for_multisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_area',
            field=models.CharField(blank=True, choices=[('interview', 'Interview'), ('documents', 'Documents'), ('snapshots', 'Snapshots'), ('information', 'Information'), ('memberships', 'Memberships')], help_text='Area in the dashboard this task belongs to (determines which button is shown).', max_length=16, verbose_name='Task area'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('task', 'Task'), ('recommendation', 'Recommendation'), ('step', 'Step'), ('guidance', 'Guidance')], default='task', help_text='Type of this task (determines how it is displayed in the dashboard).', max_length=16, verbose_name='Task type'),
        ),
    ]
