# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0036_remove_subsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='title_en',
            new_name='title_lang1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='help_en',
            new_name='help_lang1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text_en',
            new_name='text_lang1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='verbose_name_en',
            new_name='verbose_name_lang1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='verbose_name_plural_en',
            new_name='verbose_name_plural_lang1',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='help_en',
            new_name='help_lang1',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='title_en',
            new_name='title_lang1',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='verbose_name_en',
            new_name='verbose_name_lang1',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='verbose_name_plural_en',
            new_name='verbose_name_plural_lang1',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='title_en',
            new_name='title_lang1',
        ),
    ]
