# Generated by Django 2.2.7 on 2019-11-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0048_catalog_help'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='catalog',
            managers=[
            ],
        ),
    ]
