# Generated by Django 2.2.18 on 2021-05-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0059_question_default_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='widget_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('yesno', 'Yes/No'), ('checkbox', 'Checkboxes'), ('radio', 'Radio buttons'), ('select', 'Select drop-down'), ('autocomplete', 'Autocomplete'), ('range', 'Range slider'), ('date', 'Date picker'), ('file', 'File upload')], help_text='Type of widget for this question.', max_length=12, verbose_name='Widget type'),
        ),
    ]
