# Generated by Django 3.2.12 on 2022-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0066_alter_question_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='locked',
            field=models.BooleanField(default=False, help_text='Designates whether this catalog (and its sections, question sets and questions) can be changed.', verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='locked',
            field=models.BooleanField(default=False, help_text='Designates whether this question set (and its questions) can be changed.', verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='section',
            name='locked',
            field=models.BooleanField(default=False, help_text='Designates whether this section (and its question sets and questions) can be changed.', verbose_name='Locked'),
        ),
    ]
