# Generated by Django 3.2.16 on 2023-01-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('questions', '0068_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this catalog (in a multi site setup).', related_name='questions_catalog_editors', related_query_name='questions_catalog_editors', to='sites.Site', verbose_name='Edited by Sites'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='The sites for which this catalog is visible (in a multi site setup).', to='sites.Site', verbose_name='Sites'),
        ),
    ]
