# Generated by Django 3.2.16 on 2023-01-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('questions', '0068_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='edited_by',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this catalog (in a multi site setup).', related_name='questions_catalog_edit', related_query_name='questions_catalog_edit', to='sites.Site', verbose_name='Editor Sites'),
        ),
        migrations.AddField(
            model_name='question',
            name='edited_by',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this question (in a multi site setup).', related_name='questions_question_edit', related_query_name='questions_question_edit', to='sites.Site', verbose_name='Sites'),
        ),
        migrations.AddField(
            model_name='question',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='The sites for which this question is visible (in a multi site setup).', related_name='questions_question_read', related_query_name='questions_question_read', to='sites.Site', verbose_name='Sites'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='edited_by',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this questionset (in a multi site setup).', related_name='questions_questionset_edit', related_query_name='questions_questionset_edit', to='sites.Site', verbose_name='Sites'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='The sites for which this questionset is visible (in a multi site setup).', related_name='questions_questionset_read', related_query_name='questions_questionset_read', to='sites.Site', verbose_name='Sites'),
        ),
        migrations.AddField(
            model_name='section',
            name='edited_by',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this section (in a multi site setup).', related_name='questions_section_edit', related_query_name='questions_section_edit', to='sites.Site', verbose_name='Sites'),
        ),
        migrations.AddField(
            model_name='section',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='The sites for which this question is visible (in a multi site setup).', related_name='questions_section_read', related_query_name='questions_section_read', to='sites.Site', verbose_name='Sites'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='The sites for which this catalog is visible (in a multi site setup).', related_name='questions_catalog_read', related_query_name='questions_catalog_read', to='sites.Site', verbose_name='Sites'),
        ),
    ]
