# Generated by Django 3.2.14 on 2023-02-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('questions', '0068_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this catalog (in a multi site setup).', related_name='catalog_editors', to='sites.Site', verbose_name='Editors'),
        ),
        migrations.AddField(
            model_name='question',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this catalog (in a multi site setup).', related_name='question_editors', to='sites.Site', verbose_name='Editors'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this catalog (in a multi site setup).', related_name='questionset_editors', to='sites.Site', verbose_name='Editors'),
        ),
        migrations.AddField(
            model_name='section',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this catalog (in a multi site setup).', related_name='section_editors', to='sites.Site', verbose_name='Editors'),
        ),
    ]
