# Generated by Django 3.2.14 on 2022-12-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0069_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The section this question set belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionsets', to='questions.section', verbose_name='Section'),
        ),
    ]
