# Generated by Django 3.2.14 on 2022-12-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0070_alter_questionset_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionset',
            field=models.ForeignKey(blank=True, help_text='The question set this question belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.questionset', verbose_name='Questionset'),
        ),
    ]
