# Generated by Django 3.2.14 on 2022-12-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0076_questionset_remove_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('uri',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionset',
            options={'ordering': ('uri',), 'verbose_name': 'Question set', 'verbose_name_plural': 'Question set'},
        ),
        migrations.AlterField(
            model_name='question',
            name='width',
            field=models.IntegerField(blank=True, help_text='Width for the widget of this question (optional, full width: 12).', null=True, verbose_name='Width'),
        ),
    ]
