# Generated by Django 3.2.14 on 2023-01-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0077_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='key',
            new_name='uri_path',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='uri',
            field=models.URLField(blank=True, help_text='The Uniform Resource Identifier of this catalog (auto-generated).', max_length=800, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='uri_path',
            field=models.CharField(blank=True, help_text='The path for the URI of this catalog.', max_length=512, verbose_name='URI Path'),
        ),
    ]
