# Generated by Django 3.2.14 on 2023-01-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0082_question_uri_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ('uri',), 'verbose_name': 'Catalog', 'verbose_name_plural': 'Catalogs'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('uri',), 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('uri',), 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
    ]
