# Generated by Django 3.2.14 on 2023-01-10 14:05

from django.db import migrations, models
import django.db.models.deletion


def run_data_migration(apps, schema_editor):
    Page = apps.get_model('questions', 'Page')

    for page in Page.objects.all():
        page.section.pages.add(page)


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0084_catalog_sections'),
    ]

    operations = [
        # remove the related_name='pages' from Section.section
        migrations.AlterField(
            model_name='page',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='pages',
            field=models.ManyToManyField(blank=True, help_text='The pages of this section.', related_name='sections', to='questions.Page', verbose_name='Pages'),
        ),
        migrations.RunPython(run_data_migration),
        migrations.RemoveField(
            model_name='page',
            name='section',
        )
    ]
