# Generated by Django 3.2.14 on 2023-01-10 14:05

from django.db import migrations, models
import django.db.models.deletion


def run_data_migration(apps, schema_editor):
    Question = apps.get_model('questions', 'Question')

    for question in Question.objects.all():
        if question.page is not None:
            question.page.questions.add(question)


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0086_page_questionsets'),
    ]

    operations = [
        # remove the related_name='questions' from Question.page
        migrations.AlterField(
            model_name='question',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='questions',
            field=models.ManyToManyField(blank=True, help_text='The questions of this page.', related_name='pages', to='questions.Question', verbose_name='Questions'),
        ),
        migrations.RunPython(run_data_migration),
        migrations.RemoveField(
            model_name='question',
            name='page',
        )
    ]
