# Generated by Django 3.2.14 on 2023-01-10 14:05

from django.db import migrations, models
import django.db.models.deletion


def run_data_migration(apps, schema_editor):
    QuestionSet = apps.get_model('questions', 'QuestionSet')

    for questionset in QuestionSet.objects.all():
        if questionset.questionset is not None:
            questionset.questionset.questionsets.add(questionset)


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0087_page_questions'),
    ]

    operations = [
        # remove the related_name='questions' from Question.page
        migrations.AlterField(
            model_name='questionset',
            name='questionset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.QuestionSet'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='questionsets',
            field=models.ManyToManyField(blank=True, help_text='The question sets of this question set.', related_name='parents', to='questions.QuestionSet', verbose_name='Question sets'),
        ),
        migrations.RunPython(run_data_migration),
        migrations.RemoveField(
            model_name='questionset',
            name='questionset',
        )
    ]
