# Generated by Django 4.2.7 on 2023-11-08 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0090_add_editors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionset",
            options={
                "ordering": ("uri",),
                "verbose_name": "Question set",
                "verbose_name_plural": "Question sets",
            },
        ),
    ]
