# Generated by Django 4.2.5 on 2023-09-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0091_alter_questionset_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='verbose_name_plural_lang1',
        ),
        migrations.RemoveField(
            model_name='page',
            name='verbose_name_plural_lang2',
        ),
        migrations.RemoveField(
            model_name='page',
            name='verbose_name_plural_lang3',
        ),
        migrations.RemoveField(
            model_name='page',
            name='verbose_name_plural_lang4',
        ),
        migrations.RemoveField(
            model_name='page',
            name='verbose_name_plural_lang5',
        ),
        migrations.RemoveField(
            model_name='question',
            name='verbose_name_plural_lang1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='verbose_name_plural_lang2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='verbose_name_plural_lang3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='verbose_name_plural_lang4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='verbose_name_plural_lang5',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='verbose_name_plural_lang1',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='verbose_name_plural_lang2',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='verbose_name_plural_lang3',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='verbose_name_plural_lang4',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='verbose_name_plural_lang5',
        ),
    ]
