# Generated by Django 4.2.7 on 2023-11-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0092_remove_verbose_name_plural"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional internal information about this question.",
                verbose_name="Comment",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="default_text_lang1",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The default text value for this question in the primary language.",
                verbose_name="Default text value (primary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="default_text_lang2",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The default text value for this question in the secondary language.",
                verbose_name="Default text value (secondary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="default_text_lang3",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The default text value for this question in the tertiary language.",
                verbose_name="Default text value (tertiary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="default_text_lang4",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The default text value for this question in the quaternary language.",
                verbose_name="Default text value (quaternary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="default_text_lang5",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The default text value for this question in the quinary language.",
                verbose_name="Default text value (quinary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="help_lang1",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for this question in the primary language.",
                verbose_name="Help (primary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="help_lang2",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for this question in the secondary language.",
                verbose_name="Help (secondary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="help_lang3",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for this question in the tertiary language.",
                verbose_name="Help (tertiary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="help_lang4",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for this question in the quaternary language.",
                verbose_name="Help (quaternary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="help_lang5",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The help text for this question in the quinary language.",
                verbose_name="Help (quinary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text_lang1",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The text for this question in the primary language.",
                verbose_name="Text (primary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text_lang2",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The text for this question in the secondary language.",
                verbose_name="Text (secondary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text_lang3",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The text for this question in the tertiary language.",
                verbose_name="Text (tertiary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text_lang4",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The text for this question in the quaternary language.",
                verbose_name="Text (quaternary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text_lang5",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The text for this question in the quinary language.",
                verbose_name="Text (quinary)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="uri",
            field=models.URLField(
                blank=True,
                default="",
                help_text="The Uniform Resource Identifier of this question (auto-generated).",
                max_length=800,
                verbose_name="URI",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="uri_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The path for the URI of this question.",
                max_length=512,
                verbose_name="URI Path",
            ),
        ),
    ]
