# Generated by Django 4.2.6 on 2023-12-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0092_remove_verbose_name_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='help_lang1',
            field=models.TextField(blank=True, help_text='The help text for this catalog (in the primary language).', verbose_name='Help (primary)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='help_lang2',
            field=models.TextField(blank=True, help_text='The help text for this catalog (in the secondary language).', verbose_name='Help (secondary)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='help_lang3',
            field=models.TextField(blank=True, help_text='The help text for this catalog (in the tertiary language).', verbose_name='Help (tertiary)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='help_lang4',
            field=models.TextField(blank=True, help_text='The help text for this catalog (in the quaternary language).', verbose_name='Help (quaternary)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='help_lang5',
            field=models.TextField(blank=True, help_text='The help text for this catalog (in the quinary language).', verbose_name='Help (quinary)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title_lang1',
            field=models.CharField(blank=True, help_text='The title for this catalog (in the primary language).', max_length=256, verbose_name='Title (primary)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title_lang2',
            field=models.CharField(blank=True, help_text='The title for this catalog (in the secondary language).', max_length=256, verbose_name='Title (secondary)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title_lang3',
            field=models.CharField(blank=True, help_text='The title for this catalog (in the tertiary language).', max_length=256, verbose_name='Title (tertiary)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title_lang4',
            field=models.CharField(blank=True, help_text='The title for this catalog (in the quaternary language).', max_length=256, verbose_name='Title (quaternary)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title_lang5',
            field=models.CharField(blank=True, help_text='The title for this catalog (in the quinary language).', max_length=256, verbose_name='Title (quinary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='help_lang1',
            field=models.TextField(blank=True, help_text='The help text for this page (in the primary language).', verbose_name='Help (primary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='help_lang2',
            field=models.TextField(blank=True, help_text='The help text for this page (in the secondary language).', verbose_name='Help (secondary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='help_lang3',
            field=models.TextField(blank=True, help_text='The help text for this page (in the tertiary language).', verbose_name='Help (tertiary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='help_lang4',
            field=models.TextField(blank=True, help_text='The help text for this page (in the quaternary language).', verbose_name='Help (quaternary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='help_lang5',
            field=models.TextField(blank=True, help_text='The help text for this page (in the quinary language).', verbose_name='Help (quinary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_lang1',
            field=models.CharField(blank=True, help_text='The title for this page (in the primary language).', max_length=256, verbose_name='Title (primary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_lang2',
            field=models.CharField(blank=True, help_text='The title for this page (in the secondary language).', max_length=256, verbose_name='Title (secondary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_lang3',
            field=models.CharField(blank=True, help_text='The title for this page (in the tertiary language).', max_length=256, verbose_name='Title (tertiary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_lang4',
            field=models.CharField(blank=True, help_text='The title for this page (in the quaternary language).', max_length=256, verbose_name='Title (quaternary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_lang5',
            field=models.CharField(blank=True, help_text='The title for this page (in the quinary language).', max_length=256, verbose_name='Title (quinary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='verbose_name_lang1',
            field=models.CharField(blank=True, help_text='The name displayed for this page (in the primary language).', max_length=256, verbose_name='Name (primary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='verbose_name_lang2',
            field=models.CharField(blank=True, help_text='The name displayed for this page (in the secondary language).', max_length=256, verbose_name='Name (secondary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='verbose_name_lang3',
            field=models.CharField(blank=True, help_text='The name displayed for this page (in the tertiary language).', max_length=256, verbose_name='Name (tertiary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='verbose_name_lang4',
            field=models.CharField(blank=True, help_text='The name displayed for this page (in the quaternary language).', max_length=256, verbose_name='Name (quaternary)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='verbose_name_lang5',
            field=models.CharField(blank=True, help_text='The name displayed for this page (in the quinary language).', max_length=256, verbose_name='Name (quinary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Additional internal information about this question.', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='default_text_lang1',
            field=models.TextField(blank=True, default='', help_text='The default text value for this question (in the primary language).', verbose_name='Default text value (primary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='default_text_lang2',
            field=models.TextField(blank=True, default='', help_text='The default text value for this question (in the secondary language).', verbose_name='Default text value (secondary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='default_text_lang3',
            field=models.TextField(blank=True, default='', help_text='The default text value for this question (in the tertiary language).', verbose_name='Default text value (tertiary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='default_text_lang4',
            field=models.TextField(blank=True, default='', help_text='The default text value for this question (in the quaternary language).', verbose_name='Default text value (quaternary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='default_text_lang5',
            field=models.TextField(blank=True, default='', help_text='The default text value for this question (in the quinary language).', verbose_name='Default text value (quinary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_lang1',
            field=models.TextField(blank=True, default='', help_text='The help text for this question (in the primary language).', verbose_name='Help (primary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_lang2',
            field=models.TextField(blank=True, default='', help_text='The help text for this question (in the secondary language).', verbose_name='Help (secondary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_lang3',
            field=models.TextField(blank=True, default='', help_text='The help text for this question (in the tertiary language).', verbose_name='Help (tertiary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_lang4',
            field=models.TextField(blank=True, default='', help_text='The help text for this question (in the quaternary language).', verbose_name='Help (quaternary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_lang5',
            field=models.TextField(blank=True, default='', help_text='The help text for this question (in the quinary language).', verbose_name='Help (quinary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_lang1',
            field=models.TextField(blank=True, default='', help_text='The text for this question (in the primary language).', verbose_name='Text (primary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_lang2',
            field=models.TextField(blank=True, default='', help_text='The text for this question (in the secondary language).', verbose_name='Text (secondary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_lang3',
            field=models.TextField(blank=True, default='', help_text='The text for this question (in the tertiary language).', verbose_name='Text (tertiary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_lang4',
            field=models.TextField(blank=True, default='', help_text='The text for this question (in the quaternary language).', verbose_name='Text (quaternary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_lang5',
            field=models.TextField(blank=True, default='', help_text='The text for this question (in the quinary language).', verbose_name='Text (quinary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='uri',
            field=models.URLField(blank=True, default='', help_text='The Uniform Resource Identifier of this question (auto-generated).', max_length=800, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='question',
            name='uri_path',
            field=models.CharField(blank=True, default='', help_text='The path for the URI of this question.', max_length=512, verbose_name='URI Path'),
        ),
        migrations.AlterField(
            model_name='question',
            name='verbose_name_lang1',
            field=models.CharField(blank=True, help_text='The name displayed for this question (in the primary language).', max_length=256, verbose_name='Name (primary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='verbose_name_lang2',
            field=models.CharField(blank=True, help_text='The name displayed for this question (in the secondary language).', max_length=256, verbose_name='Name (secondary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='verbose_name_lang3',
            field=models.CharField(blank=True, help_text='The name displayed for this question (in the tertiary language).', max_length=256, verbose_name='Name (tertiary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='verbose_name_lang4',
            field=models.CharField(blank=True, help_text='The name displayed for this question (in the quaternary language).', max_length=256, verbose_name='Name (quaternary)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='verbose_name_lang5',
            field=models.CharField(blank=True, help_text='The name displayed for this question (in the quinary language).', max_length=256, verbose_name='Name (quinary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='help_lang1',
            field=models.TextField(blank=True, help_text='The help text for this question set (in the primary language).', verbose_name='Help (primary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='help_lang2',
            field=models.TextField(blank=True, help_text='The help text for this question set (in the secondary language).', verbose_name='Help (secondary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='help_lang3',
            field=models.TextField(blank=True, help_text='The help text for this question set (in the tertiary language).', verbose_name='Help (tertiary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='help_lang4',
            field=models.TextField(blank=True, help_text='The help text for this question set (in the quaternary language).', verbose_name='Help (quaternary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='help_lang5',
            field=models.TextField(blank=True, help_text='The help text for this question set (in the quinary language).', verbose_name='Help (quinary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='title_lang1',
            field=models.CharField(blank=True, help_text='The title for this question set (in the primary language).', max_length=256, verbose_name='Title (primary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='title_lang2',
            field=models.CharField(blank=True, help_text='The title for this question set (in the secondary language).', max_length=256, verbose_name='Title (secondary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='title_lang3',
            field=models.CharField(blank=True, help_text='The title for this question set (in the tertiary language).', max_length=256, verbose_name='Title (tertiary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='title_lang4',
            field=models.CharField(blank=True, help_text='The title for this question set (in the quaternary language).', max_length=256, verbose_name='Title (quaternary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='title_lang5',
            field=models.CharField(blank=True, help_text='The title for this question set (in the quinary language).', max_length=256, verbose_name='Title (quinary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='verbose_name_lang1',
            field=models.CharField(blank=True, help_text='The name displayed for this question set (in the primary language).', max_length=256, verbose_name='Name (primary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='verbose_name_lang2',
            field=models.CharField(blank=True, help_text='The name displayed for this question set (in the secondary language).', max_length=256, verbose_name='Name (secondary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='verbose_name_lang3',
            field=models.CharField(blank=True, help_text='The name displayed for this question set (in the tertiary language).', max_length=256, verbose_name='Name (tertiary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='verbose_name_lang4',
            field=models.CharField(blank=True, help_text='The name displayed for this question set (in the quaternary language).', max_length=256, verbose_name='Name (quaternary)'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='verbose_name_lang5',
            field=models.CharField(blank=True, help_text='The name displayed for this question set (in the quinary language).', max_length=256, verbose_name='Name (quinary)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_lang1',
            field=models.CharField(blank=True, help_text='The title for this section (in the primary language).', max_length=256, verbose_name='Title (primary)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_lang2',
            field=models.CharField(blank=True, help_text='The title for this section (in the secondary language).', max_length=256, verbose_name='Title (secondary)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_lang3',
            field=models.CharField(blank=True, help_text='The title for this section (in the tertiary language).', max_length=256, verbose_name='Title (tertiary)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_lang4',
            field=models.CharField(blank=True, help_text='The title for this section (in the quaternary language).', max_length=256, verbose_name='Title (quaternary)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_lang5',
            field=models.CharField(blank=True, help_text='The title for this section (in the quinary language).', max_length=256, verbose_name='Title (quinary)'),
        ),
    ]
