# Generated by Django 4.2.8 on 2024-06-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0093_alter_help_text_and_set_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='short_title_lang1',
            field=models.CharField(blank=True, help_text='The short title for this section (in the primary language), used in the navigation.', max_length=32, verbose_name='Short title (primary)'),
        ),
        migrations.AddField(
            model_name='section',
            name='short_title_lang2',
            field=models.CharField(blank=True, help_text='The short title for this section (in the secondary language), used in the navigation.', max_length=32, verbose_name='Short title (secondary)'),
        ),
        migrations.AddField(
            model_name='section',
            name='short_title_lang3',
            field=models.CharField(blank=True, help_text='The short title for this section (in the tertiary language), used in the navigation.', max_length=32, verbose_name='Short title (tertiary)'),
        ),
        migrations.AddField(
            model_name='section',
            name='short_title_lang4',
            field=models.CharField(blank=True, help_text='The short title for this section (in the quaternary language), used in the navigation.', max_length=32, verbose_name='Short title (quaternary)'),
        ),
        migrations.AddField(
            model_name='section',
            name='short_title_lang5',
            field=models.CharField(blank=True, help_text='The short title for this section (in the quinary language), used in the navigation.', max_length=32, verbose_name='Short title (quinary)'),
        ),
    ]
