# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_not_null'),
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='option',
            field=models.ForeignKey(blank=True, null=True, db_constraint=False, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='options.Option'),
        ),
    ]
