# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='options.Option'),
        ),
    ]
