# Generated by Django 2.2.7 on 2019-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_data_migration'),
        ('projects', '0030_project_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, help_text='The tasks that will be used for this project.', to='tasks.Task', verbose_name='Tasks'),
        ),
    ]
