# Generated by Django 3.2.14 on 2022-12-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuation',
            name='questionset',
            field=models.ForeignKey(help_text='The question set for this continuation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.questionset', verbose_name='Question set'),
        ),
    ]
