# Generated by Django 3.2.14 on 2022-12-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0074_data_migration'),
        ('projects', '0053_alter_continuation_questionset'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuation',
            name='page',
            field=models.ForeignKey(help_text='The page for this continuation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.page', verbose_name='Page'),
        ),
    ]
