# Generated by Django 3.2.14 on 2022-12-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuation',
            name='questionset',
        ),
    ]
