# Generated by Django 3.2.14 on 2023-02-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_remove_continuation_questionset'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='set_collection',
            field=models.BooleanField(help_text='Indicates if this value was entered as part of a set (important for conditions).', null=True, verbose_name='Set collection'),
        ),
    ]
