# Generated by Django 3.2.14 on 2023-05-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_task_locked'),
        ('views', '0026_view_locked'),
        ('projects', '0057_value_set_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, help_text='The tasks that will be used for this project.', related_name='projects', through='projects.Issue', to='tasks.Task', verbose_name='Tasks'),
        ),
        migrations.AlterField(
            model_name='project',
            name='views',
            field=models.ManyToManyField(blank=True, help_text='The views that will be used for this project.', related_name='projects', to='views.View', verbose_name='Views'),
        ),
    ]
