# Generated by Django 3.2.19 on 2023-08-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_count',
            field=models.IntegerField(help_text='The number of values for the progress bar.', null=True, verbose_name='Progress count'),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_total',
            field=models.IntegerField(help_text='The total number of expected values for the progress bar.', null=True, verbose_name='Progress total'),
        ),
    ]
