# Generated by Django 4.2.20 on 2025-06-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ('project', 'snapshot', 'attribute', 'set_prefix', 'set_index', 'collection_index'), 'verbose_name': 'Value', 'verbose_name_plural': 'Values'},
        ),
    ]
