# Generated by Django 5.2.14 on 2026-08-13 15:22

from django.db import migrations, models

from rdmo.core.plugins import get_plugin


def set_integration_titles(apps, schema_editor):
    Integration = apps.get_model('projects', 'Integration')

    for integration in Integration.objects.all():
        provider = get_plugin('PROJECT_ISSUE_PROVIDERS', integration.provider_key)
        integration.title = f'{provider.label} {integration.pk}'
        integration.save(update_fields=('title',))


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_alter_value_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='title',
            field=models.CharField(
                help_text='The title for this integration.',
                max_length=256,
                null=True,
                verbose_name='Title',
            ),
        ),
        migrations.RunPython(
            set_integration_titles,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='integration',
            name='title',
            field=models.CharField(
                help_text='The title for this integration.',
                max_length=256,
                verbose_name='Title',
            ),
        ),
    ]
