# Generated by Django 4.2 on 2026-05-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('projects', '0063_alter_value_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='plugin',
            field=models.ForeignKey(
                blank=True,
                help_text='The issue provider plugin for this integration.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='integrations',
                to='config.plugin',
                verbose_name='Plugin',
            ),
        ),
        migrations.RemoveField(
            model_name='integration',
            name='provider_key',
        ),
    ]
