# Generated by Django 4.2 on 2026-05-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def build_plugin_uri(uri_prefix, uri_path):
    return f"{uri_prefix.rstrip('/')}/plugins/{uri_path.strip('/')}"


def migrate_legacy_issue_provider_settings(Plugin):
    for key, label, python_path in getattr(settings, 'PROJECT_ISSUE_PROVIDERS', []):
        if Plugin.objects.filter(plugin_type='project_issue_provider', url_name=key).exists():
            continue

        uri_prefix = settings.DEFAULT_URI_PREFIX
        uri_path = f"project_issue_provider/{key}"
        Plugin.objects.create(
            uri=build_plugin_uri(uri_prefix, uri_path),
            uri_prefix=uri_prefix,
            uri_path=uri_path,
            title_lang1=label,
            available=True,
            python_path=python_path,
            plugin_type='project_issue_provider',
            url_name=key,
        )


def migrate_integration_provider_key(apps, schema_editor):
    Integration = apps.get_model('projects', 'Integration')
    Plugin = apps.get_model('config', 'Plugin')

    migrate_legacy_issue_provider_settings(Plugin)

    providers = {
        plugin.url_name: plugin.id
        for plugin in Plugin.objects.filter(plugin_type='project_issue_provider').exclude(url_name='')
    }

    if not providers:
        return

    integrations = Integration.objects.exclude(provider_key='').values('id', 'provider_key')
    for integration in integrations:
        plugin_id = providers.get(integration['provider_key'])
        if plugin_id is None:
            continue

        Integration.objects.filter(id=integration['id']).update(plugin_id=plugin_id)


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('projects', '0063_alter_value_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='plugin',
            field=models.ForeignKey(
                blank=True,
                help_text='The issue provider plugin for this integration.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='integrations',
                to='config.plugin',
                verbose_name='Plugin',
            ),
        ),
        migrations.RunPython(migrate_integration_provider_key, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='integration',
            name='provider_key',
        ),
    ]
