# Generated by Django 5.2.17 on 2026-09-08 10:02

import django.db.models.deletion
from django.db import migrations, models


def increment_depth(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    db_alias = schema_editor.connection.alias
    for p in Project.objects.using(db_alias).all():
        p.depth += 1
        p.save()

def decrement_depth(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    db_alias = schema_editor.connection.alias
    for p in Project.objects.using(db_alias).all():
        p.depth -= 1
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_integration_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('tree_id', 'depth', 'title'), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='level',
            new_name='depth',
        ),
        migrations.AlterField(
            model_name='project',
            name='depth',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.RunPython(
            increment_depth,
            decrement_depth
        ),
        migrations.RenameField(
            model_name='project',
            old_name='rght',
            new_name='rgt',
        ),
        migrations.AlterField(
            model_name='project',
            name='rgt',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lft',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent project of this project.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='projects.project', verbose_name='Parent project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
