# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0011_refactoring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ('uri',), 'permissions': (('view_condition', 'Can view Condition'),), 'verbose_name': 'Condition', 'verbose_name_plural': 'Conditions'},
        ),
    ]
