# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_attributeentity_parent_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeentity',
            name='full_title',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
