# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0023_fix_label'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attribute',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='attributeentity',
            managers=[
            ],
        ),
    ]
