# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0026_refactoring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeentity',
            options={'ordering': ('uri',), 'verbose_name': 'Attribute entity', 'verbose_name_plural': 'Attribute entities'},
        ),
    ]
