# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('domain', '0037_remove_attribute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttributeEntity',
            new_name='Attribute',
        ),
    ]
