# Generated by Django 3.2.12 on 2022-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0047_attribute_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='locked',
            field=models.BooleanField(default=False, help_text='Designates whether this attribute (and its descendants) can be changed.', verbose_name='Locked'),
        ),
    ]
