# Generated by Django 3.2.16 on 2023-02-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('domain', '0048_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='The sites that can edit this attribute (in a multi site setup).', related_name='attributes_as_editor', to='sites.Site', verbose_name='Editors'),
        ),
    ]
