# Generated by Django 5.2.17 on 2026-09-09 10:23

import django.db.models.deletion
from django.db import migrations, models

def increment_depth(apps, schema_editor):
    Attribute = apps.get_model("domain", "Attribute")
    db_alias = schema_editor.connection.alias
    for p in Attribute.objects.using(db_alias).all():
        p.depth += 1
        p.save()

def decrement_depth(apps, schema_editor):
    Attribute = apps.get_model("domain", "Attribute")
    db_alias = schema_editor.connection.alias
    for p in Attribute.objects.using(db_alias).all():
        p.depth -= 1
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0049_attribute_add_editors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='level',
            new_name='depth',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='depth',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.RunPython(
            increment_depth,
            decrement_depth
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='rght',
            new_name='rgt',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='rgt',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='lft',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent attribute in the domain model.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='domain.attribute', verbose_name='Parent attribute'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
