# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_de_to_lang2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfield',
            name='help_lang1',
            field=models.TextField(blank=True, help_text='The help text to be displayed next to the input element in the primary language.', null=True, verbose_name='Help (primary)'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='help_lang2',
            field=models.TextField(blank=True, help_text='The help text to be displayed next to the input element in the secondary language.', null=True, verbose_name='Help (secondary)'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='required',
            field=models.BooleanField(help_text='Designates whether this additional field is required.', verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='text_lang1',
            field=models.CharField(help_text='The text for this additional field in the primary language.', max_length=256, verbose_name='Text (primary)'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='text_lang2',
            field=models.CharField(help_text='The text for this additional field in the secondary language.', max_length=256, verbose_name='Text (secondary)'),
        ),
    ]
