# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfield',
            name='help_lang1',
            field=models.TextField(blank=True, help_text='The help text to be displayed next to the input element in the primary language.', verbose_name='Help (primary)'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='help_lang2',
            field=models.TextField(blank=True, help_text='The help text to be displayed next to the input element in the secondary language.', verbose_name='Help (secondary)'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='help_lang3',
            field=models.TextField(blank=True, help_text='The help text to be displayed next to the input element in the tertiary language.', verbose_name='Help (tertiary)'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='help_lang4',
            field=models.TextField(blank=True, help_text='The help text to be displayed next to the input element in the quaternary language.', verbose_name='Help (quaternary)'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='help_lang5',
            field=models.TextField(blank=True, help_text='The help text to be displayed next to the input element in the quinary language.', verbose_name='Help (quinary)'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='text_lang1',
            field=models.CharField(blank=True, help_text='The text for this additional field in the primary language.', max_length=256, verbose_name='Text (primary)'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='text_lang2',
            field=models.CharField(blank=True, help_text='The text for this additional field in the secondary language.', max_length=256, verbose_name='Text (secondary)'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='text_lang3',
            field=models.CharField(blank=True, help_text='The text for this additional field in the tertiary language.', max_length=256, verbose_name='Text (tertiary)'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='text_lang4',
            field=models.CharField(blank=True, help_text='The text for this additional field in the quaternary language.', max_length=256, verbose_name='Text (quaternary)'),
        ),
        migrations.AlterField(
            model_name='additionalfield',
            name='text_lang5',
            field=models.CharField(blank=True, help_text='The text for this additional field in the quinary language.', max_length=256, verbose_name='Text (quinary)'),
        ),
    ]
