# Generated by Django 3.2.16 on 2023-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('accounts', '0019_delete_proxyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='editor',
            field=models.ManyToManyField(blank=True, help_text='The sites for which this user is an editor.', related_name='editors', to='sites.Site', verbose_name='Editor'),
        ),
        migrations.AddField(
            model_name='role',
            name='reviewer',
            field=models.ManyToManyField(blank=True, help_text='The sites for which this user is a reviewer.', related_name='reviewers', to='sites.Site', verbose_name='Reviewer'),
        ),
    ]
