# Generated by Django 4.2.17 on 2025-01-23 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentfieldvalue',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consentfieldvalue',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated'),
            preserve_default=False,
        ),
    ]
