# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeentity',
            name='parent_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='domain.AttributeEntity'),
        ),
    ]
