# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributeentity',
            old_name='parent_entity',
            new_name='parent',
        ),
    ]
