# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0009_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='help_en',
            new_name='help_lang1',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='title_en',
            new_name='title_lang1',
        ),
    ]
