# Generated by Django 2.2rc1 on 2019-03-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0015_remove_null_true'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='view',
            options={'ordering': ('key',), 'verbose_name': 'View', 'verbose_name_plural': 'Views'},
        ),
    ]
