# Generated by Django 2.2.2 on 2019-07-01 16:00

from django.db import migrations
import django.db.models.manager
import rdmo.views.managers


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0019_view_groups'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='view',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', rdmo.views.managers.ViewManager()),
            ],
        ),
    ]
