# Generated by Django 2.2.7 on 2019-11-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0047_manager'),
        ('views', '0020_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='catalogs',
            field=models.ManyToManyField(blank=True, help_text='The catalogs this view can be used with. An empty list implies that this view can be used with every catalog.', to='questions.Catalog', verbose_name='Catalogs'),
        ),
    ]
