# Generated by Django 2.2.13 on 2020-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0024_sites_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='available',
            field=models.BooleanField(default=True, help_text='Designates whether this view is generally available for projects.', verbose_name='Available'),
        ),
    ]
