# Generated by Django 4.2.6 on 2023-11-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0028_uri_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='order',
            field=models.IntegerField(default=0, help_text='The position of this view in lists.', verbose_name='Order'),
        ),
    ]
